CREATE SEQUENCE CLIENT_SEQUENCE START WITH 20 INCREMENT BY 1;
CREATE SEQUENCE ASSURANCE_SEQUENCE START WITH 20 INCREMENT BY 1;
CREATE SEQUENCE CONTACT_SEQUENCE START WITH 20 INCREMENT BY 1;
CREATE SEQUENCE ECHEANCE_SEQUENCE START WITH 20 INCREMENT BY 1;
CREATE SEQUENCE SINISTRE_SEQUENCE START WITH 20 INCREMENT BY 1;

CREATE TABLE CLIENT(
    typeClient varchar(2),
    idClient INTEGER GENERATED BY DEFAULT AS IDENTITY (start with 1),
    nom varchar(20),
    prenom varchar(20),
    dateNaissance varchar(10),
    siren varchar(9),
    PRIMARY KEY (idClient)
);

CREATE TABLE COMPTEBANCAIRE(
    iban varchar(34),
    proprietaire INTEGER,
    bic varchar(11),
    PRIMARY KEY (iban),
    FOREIGN KEY (proprietaire) REFERENCES CLIENT(idClient)
);

CREATE TABLE ASSURANCE(
    typeAssurance varchar(2),
    idAssurance INTEGER GENERATED BY DEFAULT AS IDENTITY (start with 1),
    dateSouscription date,
    dateAnniversaire date,
    datePrelevement date,
    adresseAssuree varchar(50),
    valeurCouverture integer,
    immatriculation varchar(7),
    bonusMalus integer,
    idAssure integer,
    PRIMARY KEY (idAssurance)
);


CREATE TABLE CONTACT(
    idContact INTEGER GENERATED BY DEFAULT AS IDENTITY (start with 1),
    client INTEGER,
    cType varchar(20),
    valeur varchar(50),
    PRIMARY KEY (idContact),
    FOREIGN KEY (client) REFERENCES CLIENT(idClient)
);

CREATE TABLE ECHEANCES(
    idEcheance integer GENERATED BY DEFAULT AS IDENTITY (start with 1),
    assuranceLiee integer,
    prix integer,
    dateEmission date,
    datePaiement date,
    dateEmissionFacture date,
    PRIMARY KEY (idEcheance),
    FOREIGN KEY (assuranceLiee) REFERENCES ASSURANCE(idAssurance)
);

CREATE TABLE SINISTRE(
    idSinistre integer GENERATED BY DEFAULT AS IDENTITY (start with 1),
    dateDuSinistre date,
    titre varchar(20),
    description varchar(250),
    photoTitre varchar(250),
    sAssuranceLiee integer,
    PRIMARY KEY (idSinistre),
    FOREIGN KEY (sAssuranceLiee) REFERENCES ASSURANCE(idAssurance)
);

ALTER TABLE CLIENT 
ADD COLUMN ibanComptePrincipal varchar(34);

ALTER TABLE CLIENT 
ADD FOREIGN KEY (ibanComptePrincipal) 
REFERENCES COMPTEBANCAIRE(iban);

create TABLE CLIENT_ASSURANCE(
    idClient INTEGER,
    idAssurance INTEGER,
    PRIMARY KEY (idClient, idAssurance),
    FOREIGN KEY (idClient) REFERENCES CLIENT(idClient),
    FOREIGN KEY (idAssurance) REFERENCES ASSURANCE(idAssurance)
);
